[package]
name = "peptide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphics = { path = "../graphics_wgpu" }
lin-alg2 = { path = "../lin_alg" }

# We use `winit` here to import `winit` events, for passing to
# the renderer. todo: Re-export these from the graphics lib instead?
winit = "^0.27.2"

egui = "^0.19.0"
#egui_demo_lib = "^0.19" # todo: temp