[package]
name = "peptide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphics = { path = "../graphics_wgpu" }
lin_alg2 = { path = "../lin_alg" }

winit = "^0.27.2"

# todo: Should this GUI lib be in the engine or here?
#egui = "^0.19.0"
eframe = "^0.19.0" # todo what?
# todo: Which of these egui integrations do you want?
egui-winit = "^0.19.0"
#egui-wgpu = "^0.19.0"
