[package]
name = "peptide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "^0.7.0"

# Git so we can use the official examples.
#bevy = { git = "https://github.com/bevyengine/bevy" }
#gdnative = "0.10.0"
#graphics = { path = "../graphics_wgpu" }
